services:
  web:
    container_name: node-container
    depends_on:
      - mongo
      - redis
    ports:
      - "4000:4000"
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "8081:8081"

  redis:
    image: redis:6.2-alpine
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    env_file:
      - .env
volumes:
  mongo_data:
  cache:
